[package]
name = "dedup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.24"
hex = "0.4.3"
num_cpus = "1.15.0"
rusqlite = "0.29.0"
sha2 = "0.10.6"
